=== hiddenPeople/Study/src/hr.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!--!ELEMENT是设置标签-->
        <!ELEMENT hr (employee+)>
        <!--子标签严格按照该顺序来-->
        <!ELEMENT employee  (name,age,salary,department)>
        <!--#PCDATA是设置标签的内容为文本格式-->
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT salary (#PCDATA)>
        <!ELEMENT department (dname,address)>
        <!ELEMENT dname (#PCDATA)>
        <!ELEMENT address (city)>
        <!ELEMENT city (#PCDATA)>
        <!--!ATTLIST设置标签属性-->
        <!ATTLIST employee no CDATA "">

=== hiddenPeople/Study/src/hr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hr SYSTEM "hr.dtd">
<!--公司员工数据-->
<hr>
    <employee no="0001">
        <name>James</name>
        <age>30</age>
        <salary>5000</salary>
        <department>
            <dname>IT</dname>
            <address>
                <city>London</city>
            </address>
        </department>
    </employee>
    <employee no="0002">
        <name>Mary</name>
        <age>28</age>
        <salary>6000</salary>
        <department>
            <dname>HR</dname>
            <address>
                <city>New York</city>
            </address>
        </department>
    </employee>
</hr>
