=== hiddenPeople/Study/src/hr.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--这是定死的标准,xmlns是一个约束，约束是hr.xsd文件，约束的根标签是schema-->
<!--约束的命名空间是http://www.example.org/hr（命名空间必须是网址，可以是虚构的），这里可以不用写一个可以访问的地址-->
<!--        elementFormDefault是一个全局的约束-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/hr"
        elementFormDefault="qualified">
    <!--    一个emement标签就是说明一个xml的标签，此时代表父标签-->
    <element name="hr">
        <!--        complexType代表复杂标签，说明该标签节点下还有其他子标签-->
        <complexType>
            <!--            代表该标签下子标签的顺序，通常与complexType配合使用-->
            <sequence>
                <!--                默认是string，minOccurs代表该标签最少出现的次数，maxOccurs代表最多出现的次数-->
                <element name="employee" minOccurs="1" maxOccurs="99999">
                    <complexType>
                        <sequence>
                            <!--                            type代表标签文本类型-->
                            <element name="name" type="string"/>
                            <element name="age">
                                <!--                                simpleType代表简单类型-->
                                <simpleType>
                                    <!--                                    restriction代表约束-->
                                    <restriction base="integer">
                                        <!--                                        这是最小包含值包含18-->
                                        <minInclusive value="18"/>
                                        <!--                                        这是最大包含值包含65-->
                                        <maxInclusive value="65"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="salary" type="integer"/>
                            <element name="department">
                                <complexType>
                                    <sequence>
                                        <element name="dname" type="string"/>
                                        <element name="address">
                                            <complexType>
                                                <sequence>
                                                    <element name="city" type="string"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <!--                        attribute代表属性标签，use代表属性是否必填-->
                        <attribute name="no" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== hiddenPeople/Study/src/hr-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--公司员工数据-->
<!--第一个xmlns是自己在XSD中写的命名空间，-->
<!--第二个xmlns:xsi是XML Schema Instance，用来指定XML实例文档的XML Schema。是W3C指定的schema用来加载本地的XSD文件-->
<!--第三个xmlns:第一个参数是本地xsd的命名空间，第二个参数则是本地HR.xsd文件的名称-->
<hr xmlns="http://www.example.org/hr"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/hr hr.xsd">
    <employee no="0001">
        <name>James</name>
        <age>30</age>
        <salary>5000</salary>
        <department>
            <dname>IT</dname>
            <address>
                <city>London</city>
            </address>
        </department>
    </employee>
    <employee no="0002">
        <name>Mary</name>
        <age>28</age>
        <salary>6000</salary>
        <department>
            <dname>HR</dname>
            <address>
                <city>New York</city>
            </address>
        </department>
    </employee>
</hr>
